settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: astig-bioph-org # unique identifier
    name: AstigBio
    description: 'My Main Website Domain Status.' # default=empty
    url: 'https://astig.bioph.org/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: astigspectrum-sonicspectrum-org
    name: AstigRadio
    description: 'My Main Website Domain Status.'
    url: 'https://astigspectrum.sonicspectrum.org/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: astigflowers-myhomedns-net
    name: AstigVirtualGarden
    url: 'https://astigflowers.myhomedns.net/'
    method: GET
    expectStatus: 200
    linkable: true
